import React, { useState } from 'react';
import Head from 'next/head'

import profiles from '../../json/profiles'; 
import OptionView from './_components/Options/OptionView';
import ContentView from './_components/Content/ContentView';
import SettingView from './_components/Settings/SettingView';


export default function Editor() {
 

    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex h-full bg-gradient-to-r from-blue-500 to-pink-500 ">

            {/* <div className="relative">
                <aside className="flex flex-col relative sidebar-scrollbar overflow-y-auto h-full w-[255px] bg-[#000]">
                    <OptionView />
                </aside>
            </div> */}

            <div className="relative">
                <aside className="flex flex-col relative overflow-hidden h-full w-[255px] bg-[#000]">
                    <SettingView />
                </aside>
            </div>


            <section className="flex p-8 h-full w-full items-center justify-center">
                <ContentView />
            </section>

          
        </main>
        </>
    )
}
