import React, { useState } from 'react';
import Head from 'next/head'

import profiles from '../../json/profiles'; 
import OptionView from './_components/Options/OptionView';
import ContentView from './_components/Content/ContentView';
import SettingView from './_components/Settings/SettingView';
import { useTweetTabs } from '../../context/TweetTabsInfo';


export default function Editor() {
    const { setTwitterThemeTo } = useTweetTabs();

    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="relative overflow-y-hidden h-screen">
        <div className="flex flex-col h-full overflow-hidden">

            <nav className="bg-black w-full flex justify-between items-center">
                <div className="p-2">
                    <h1 className="text-2xl text-gray-300 font-bold">TweetCrafter</h1>
                </div>
                <div className="space-x-2 flex">

                    <div className="flex">
                        <button onClick={() => setTwitterThemeTo('default')} className="text-gray-300 bg-gray-500 rounded-sm text-sm px-3 py-1 w-auto">Default</button>
                        <button onClick={() => setTwitterThemeTo('dim')} className="text-gray-300 bg-gray-500 rounded-sm text-sm px-3 py-1 w-auto">Dim</button>
                        <button onClick={() => setTwitterThemeTo('lights-out')} className="text-gray-300 bg-gray-500 rounded-sm text-sm px-3 py-1 w-auto">Lights Out</button>
                    </div>

                    <button className="text-gray-300 bg-indigo-500 rounded-sm text-sm px-3 py-1 w-auto">Share</button>
                    <button className="text-gray-300 bg-indigo-500 rounded-sm text-sm px-3 py-1 w-auto">Preview Image</button>
                    <button className="text-gray-300 bg-indigo-500 rounded-sm text-sm px-3 py-1 w-auto">Download Image</button>
                </div>
            </nav>

            <main className="flex flex-row h-full overflow-hidden relative bg-gradient-to-r from-blue-500 to-pink-500 ">
                <div className="relative ">
                <aside className="flex flex-col relative overflow-hidden h-full w-[255px] bg-[#000]">
                    <div className="overflow-y-auto">
                        <SettingView />
                    </div>
                </aside>
                </div>
 
                <section className="relative overflow-y-auto h-full w-full">
                <div className="relative flex overflow-y-auto h-full w-full items-center justify-center">
                    <ContentView />
                </div> 
                </section>
            </main>

        </div>
        </div>
        </>
    )
}
