import React, { useState } from 'react';
import Head from 'next/head'
 
import ContentView from './_components/Content/ContentView';
import SettingView from './_components/Settings/SettingView';
import HeaderIndex from './_components/Header/HeaderIndex';

export default function Editor() {
     // @ts-ignore
  
    // const { activeTab, setActiveTab, mainProfile, twitterTheme } = useTweetTabs();
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="relative overflow-y-hidden h-screen">
        <div className="flex flex-col h-full overflow-hidden">

            <HeaderIndex />

            <main className="flex flex-row h-full overflow-hidden relative bg-gradient-to-r from-blue-500 to-pink-500 ">
                <div className="relative ">
                <aside className="flex flex-col relative overflow-hidden h-full w-[306px] bg-[#000]">
                    <div className="overflow-y-auto h-full">
                        <SettingView />
                    </div>
                </aside>
                </div>
 
                <section className="relative overflow-y-auto h-full w-full">
                <div className="pr-[413px] pb-[26px] relative flex overflow-y-auto h-full w-full items-center justify-center">
                    <ContentView />
                </div> 
                </section>
            </main>

        </div>
        </div>
        </>
    )
}
