import React, { useState } from 'react';
import Head from 'next/head'
import Profile from '../components/templates/Profile'
import Tweet from '../components/templates/Tweet'

import profiles from './../json/profiles'; 
import { useTweetTabs } from '../context/TweetTabsInfo';

const options = [
    {
        "id": 'profile',
        "name": "Profile",
        "thumbnail": "https://i.imgur.com/naK8pBm.png",
        "coming_soon": false,
        "component": <Profile />
    },
    {
        "id": "tweet",
        "name": "Tweet",
        "thumbnail": "https://i.imgur.com/UWmMBMa.png",
        "coming_soon": false,
        "component": <Tweet  />
    },
    {
        "id": "tweet_single",
        "name": "Tweet Single",
        "thumbnail": "https://i.imgur.com/HbklUeF.png",
        "coming_soon": true,
    },
    {
        "id": 'account_suspended',
        "name": "Account Suspended",
        "thumbnail": "https://i.imgur.com/HbklUeF.png",
        "coming_soon": true,
    },
    {
        "id": "pool",
        "name": "Pool",
        "thumbnail": "https://i.imgur.com/HbklUeF.png",
        "coming_soon": true,
    },
    {
        "id": "relevant_people",
        "name": "Relevant People",
        "thumbnail": "https://i.imgur.com/HbklUeF.png",
        "coming_soon": true,
    }
]


function Option(props: any) {
    const option = props.data;
    const { activeTab, setActiveTab } = useTweetTabs();

    return (
        <div className="p-4 text-center" onClick={() => setActiveTab(option.id)}>
            <img className="rounded-xl" src={option.thumbnail} />
            <h3 className="text-gray-300">{option.name}</h3>
        </div>
    )
}

function OptionList() {
    return (
        <>
            {options.map((option) => {
                return <Option key={option.id} data={option} />
            })}
        </>
    )
}



function TabContent() {
    const { activeTab, setActiveTab } = useTweetTabs();

    switch(activeTab) {
        case 'profile':
            return <Profile data={profiles[1]} />
            break;
        case 'tweet':
            return <Tweet data={profiles[1]} />
            break;
    }
    
}


export default function Editor() {
    const [currentProfile, setCurrentProfile] = useState(profiles[1]);
    const [currentTweetType, setCurrentTweetType] = useState(1);

    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex h-full bg-gradient-to-r from-blue-500 to-pink-500 ">

            <div className="relative">
                <aside className="flex flex-col relative overflow-y-auto h-full w-[255px] bg-[#000]">
                    <OptionList />
                </aside>
            </div>

            <section className="flex p-8 h-full w-full items-center justify-center">
                <div className="flex flex-col">

                    <div className="space-y-8 flex">
                        <TabContent />
                        {/* <Profile data={currentProfile} /> */}
                        {/* <Tweet data={currentProfile} /> */}
                    </div>
                </div>
            </section>

            <div className="relative">
                <aside className="flex flex-col relative overflow-hidden h-full w-[255px] bg-[#000]">
                <div className="flex flex-col flex-1 overflow-hidden">

                    <header className="flex flex-row w-full border-b border-gray-700 mb-4">
                    <div className="p-4 flex justify-between items-center w-full">
                        <h2 className="text-gray-50 font-medium">Settings | User Profiles</h2>
                    </div>
                    </header>

                    <div>


                    <div className="p-4">
                        <button className="w-full" type="button" aria-expanded="false">
                            <div className="flex justify-between items-center text-gray-50 mb-3">
                                <h2 className="text-xs font-medium">Text</h2>
                            </div>
                        </button>

                        <div className="text-gray-500" id="headlessui-disclosure-panel-:r5:">
                            <div className="grid gap-2 grid-cols-[1fr_68px]"><div>
                                <span className="text-xs text-gray-50">Font Family</span>
                                <span className="sr-only">font family</span>
                            </div>
                        <div>
                            <span className="text-xs text-gray-50">Monsserate</span>
                            <span className="sr-only">Monsserate</span></div></div><div className="grid gap-2 grid-cols-[1fr_68px]"><div><span className="text-xs text-gray-50">Font Weight</span><span className="sr-only">font weight</span></div><div><span className="text-xs text-gray-50">Bold - 700</span><span className="sr-only">bold - 700</span></div></div><div className="grid gap-2 grid-cols-[1fr_68px]"><div><span className="text-xs text-gray-50">Font Size</span><span className="sr-only">font size</span></div><div><span className="text-xs text-gray-50">18px</span><span className="sr-only">change font size. current: 18px</span></div></div><div className="grid gap-2 grid-cols-[1fr_68px]"><div><span className="text-xs text-gray-50">Color</span><span className="sr-only">Color</span></div><div><span className="text-xs text-gray-50">White</span><span className="sr-only">white</span></div></div></div></div>
                        

                        <div className="text-gray-300 p-4">
                            <h3>Size</h3>
                            <div>
                                <div>Twitter</div>
                                <div>Instagram</div>
                            </div>
                        </div>

Content
                        <div className="text-gray-300 p-4">
                            <h3>Profile</h3>
                            <div>
                                <div>Verified Badge: Yes/No</div>
                                <div>Fact Check Warning: Yes/No</div>
                            </div>
                        </div>
                        add image

                        <div className="text-gray-300 p-4">
                            <h3>Theme</h3> 
                            <div>Light | Dim | Dark</div>
                        </div>

                        <div className="text-gray-300 p-4">
                            <h3>Emoj Style</h3>

                            <div>
                                <div>Twitter: 😂😭💀</div>
                                <div>System: 😂😭💀</div>
                            </div>
                        </div>

                        <div className="text-gray-300 p-4">
                            <h3>Font</h3>
                            <div>
                                <div>Twitter Chirp Font</div>
                                <div>System Font</div>
                                <div>Inter</div>
                            </div>
                        </div>


                    </div>

                </div>
                </aside>
            </div>

        </main>
        </>
    )
}
