import Head from 'next/head'
import Image from 'next/image'


function Tweet() {
    return (
        <article className="bg-[#000000] p-4">
            <header className="flex space-x-3  mb-4">
                <img src="https://pbs.twimg.com/profile_images/2320423543/9qheijpvtu9g5dteqvvw_400x400.jpeg" className="rounded-full h-12 w-12" />
                <div className="flex flex-col">
                    <span className="text-[#e7e9ea]" contentEditable>Kim Dotcome</span>
                    <span className="text-[#71767b]">@<span contentEditable>KimDotcom</span></span>
                </div>
            </header>

            <section>
                <p contentEditable className="text-[#e7e9ea] text-[23px]" style={{"lineHeight": "1.2em"}}>
                    Hey <span className="text-[#1d9bf0]">@elonmusk</span>, it’s unwise to run a poll like this when you are now deep state enemy #1. They have the biggest bot army on Twitter. They have 100k ‘analysts’ with 30-40 accounts all voting against you. Let’s clean up and then run this poll again. The majority has faith in you. 😘
                </p>
            </section>

            <footer>
                <time dateTime="2022-12-19T12:06:26.000Z" className="text-[#71767b] py-4 block" style={{"fontSize": "15px"}}>
                    12:06 PM · Dec 19, 2022
                </time>
                <div className="flex space-x-6">
                    <p className="text-[#71767b] text-sm"><span contentEditable className="text-[#e7e9ea] font-bold">7,912</span> Retweets</p>
                    <p className="text-[#71767b] text-sm"><span contentEditable className="text-[#e7e9ea] font-bold">854</span> Quote Tweets</p>
                    <p className="text-[#71767b] text-sm"><span contentEditable className="text-[#e7e9ea] font-bold">56.1K</span> Likes</p>
                </div>
            </footer>
        </article>
    )
}

export default function Editor() {
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex h-full">

            <div className="relative">
                <aside className="flex flex-col relative overflow-hidden h-full w-[255px] bg-[#1d1d1d]">
                <div className="flex flex-col flex-1 overflow-hidden">

                    <header className="flex flex-row w-full border-b border-gray-700 mb-4">
                    <div className="p-4 flex justify-between items-center w-full">
                        <h2 className="text-gray-50 font-medium">Settings</h2>
                    </div>
                    </header>

                    <div>


                    <div className="p-4">
                        <button className="w-full" id="headlessui-disclosure-button-:r4:" type="button" aria-expanded="false">
                            <div className="flex justify-between items-center text-gray-50 mb-3">
                                <h2 className="text-xs font-medium">Text</h2>
                                <button className="text-gray-50 h-4 w-4">
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-full w-full" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                </button>
                            </div>
                        </button>

                        <div className="text-gray-500" id="headlessui-disclosure-panel-:r5:">
                            <div className="grid gap-2 grid-cols-[1fr_68px]"><div>
                                <span className="text-xs text-gray-50">Font Family</span>
                                <span className="sr-only">font family</span>
                            </div>
                        <div>
                            <span className="text-xs text-gray-50">Monsserate</span>
                            <span className="sr-only">Monsserate</span></div></div><div className="grid gap-2 grid-cols-[1fr_68px]"><div><span className="text-xs text-gray-50">Font Weight</span><span className="sr-only">font weight</span></div><div><span className="text-xs text-gray-50">Bold - 700</span><span className="sr-only">bold - 700</span></div></div><div className="grid gap-2 grid-cols-[1fr_68px]"><div><span className="text-xs text-gray-50">Font Size</span><span className="sr-only">font size</span></div><div><span className="text-xs text-gray-50">18px</span><span className="sr-only">change font size. current: 18px</span></div></div><div className="grid gap-2 grid-cols-[1fr_68px]"><div><span className="text-xs text-gray-50">Color</span><span className="sr-only">Color</span></div><div><span className="text-xs text-gray-50">White</span><span className="sr-only">white</span></div></div></div></div>

                        <div className="text-gray-300 p-4">
                            <h3>Profile</h3>
                            <div>
                                <div>Verified Badge: Yes/No</div>
                                <div>Fact Check Warning: Yes/No</div>
                            </div>
                        </div>

                        <div className="text-gray-300 p-4">
                            <h3>Theme</h3> 
                            <div>Light | Dim | Dark</div>
                        </div>

                        <div className="text-gray-300 p-4">
                            <h3>Emoj Style</h3>

                            <div>
                                <div>Twitter: 😂😭💀</div>
                                <div>System: 😂😭💀</div>
                            </div>
                        </div>

                        <div className="text-gray-300 p-4">
                            <h3>Font</h3>
                            <div>
                                <div>Twitter Chirp Font</div>
                                <div>System Font</div>
                                <div>Inter</div>
                            </div>
                        </div>


                    </div>

                </div>
                </aside>
            </div>

            <section className="flex bg-gradient-to-r from-blue-500 to-pink-500 h-full w-full items-center justify-center">
                <div className="max-w-[598px]">
                    <Tweet />
                </div>
            </section>

        </main>
        </>
    )
}
