import Head from 'next/head'
import Image from 'next/image' 

 

export default function Home() {
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex h-full">

            Home Page

            Have a tweet that is editable and downlodable

            have a 'to have more settings go to editor' - this is to show the prodct and let them use it on page 1

        </main>
        </>
    )
}
